const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}
module.exports = {
SESSION_ID: process.env.SESSION_ID || "E3_HACKER_MD~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMEN4cmNtanhYb3gvVDZvaU9LdVgrZTBzSUE0a2tzYzk1cGVuRmo4aC8waz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVnM4b1F1OTc3WDFIRVk1YXhZUncxUFlSUVg3d3NIR1RYWXlwTUFpQVYwdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4STJOMk1nNTNxSEY5Ny9ISER6ZzBoVG9TTGlHUVRRMzZ3SExBRlJNSW1ZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJkeHQvV0dJeDJ5Snd4bms2Wk5xbnRQWHRBQVZuWHBFUWtJMVBGcVVwWDBFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdJVUoyd2h0UnFveEN2L1lBejMwYTJCMkdXOU4wdnNxVEdPWStuSG5RbFU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZqQWpRcHkxZ05BV2FORzI5UVZFVkhiVVRYU2dpRGtFN3dHUGgrZEkwaW89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkNmbW10VEMzTG00SEtyc2RaM1B3ajN0azlHbTFMaFNqcDVrNHp6MVNtbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWDNIallMSlBiV211M0M2dWx4cGlEZ3NwR2NobFd1MU5qVkt5TkhtZHpBMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitiVEMxS1Npc2JQQkk3aXNxa3d5VU1SNGNFcFF4aFdYa1RSWW1SQ3NTbHoxdnZDK1BvWnlLajUwTlFwTCsyNW1zUTFudnRiNWdOdXd2T1l3WGJySmdRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAyLCJhZHZTZWNyZXRLZXkiOiJkQTBkbWx2Z1RiZ1Y1SjRnM3dvTjBOZ2ExdDN0Q3g0cHBBYmloODQ5NjJFPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJBVDNRVzNSSiIsIm1lIjp7ImlkIjoiOTIzMjI5ODU0NzExOjVAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiI1OTI3NDkyNzU4MzM5Nzo1QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUEhUeDVvRkVMbjA5Y1VHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiOWJkL2thQnIwK0hhbjlkUTNvY3ZrNkwyMUN3UmMvNVZMRTBxWC9CY2FpMD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiQU1HaHRib0IrQUEwMkhSOUhOZCtOZ1pSNlFTbGY3Z1lUTTREQWZoaERWdm1RL0haK0tZbDdwcTVoT3hiRHUyUXhiRER4Yi9ZbEFQUEZ1dTNDQXlkRGc9PSIsImRldmljZVNpZ25hdHVyZSI6IkY2VlVMOFJUMFZtOUlwTituaHBkYmc5SitrS0dvTVdvL0p3bmtGcHc4a0VTRDZZZHBMenlobTZtL0xiQWUwdE9QVHBqcXovcmJ4aHF1alRzaWNmU2p3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTIzMjI5ODU0NzExOjVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZlczZjVHZ2E5UGgycC9YVU42SEw1T2k5dFFzRVhQK1ZTeE5LbC93WEdvdCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FnSUJRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU3MjQ4MDYxLCJsYXN0UHJvcEhhc2giOiJQV2s1QiJ9HTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic2hWOG9nQVhNVXo4RE5SdTVtaXlLUzIrVXhyajhFWENQVTdhZGZDQngyMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLQ3VUY1VCcWw4SU9YYlp0ODJacHdMZEp0VEdDWnNXSUhuMFdpaDN0S0ZNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVZGVadUI0aDg2LzhrY1FNM2pONEF3cmdaSUQxdEtPMEUxb3FmOXJ1c2tJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtJSE5EcnR6bHJwaFV1cHVjRU9VcDNEc203d1UxblRXS1prd2hYUjVsWDQ9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitsRGgvZVJ1Qnk2ckY2NlViNHBmZWRBQkRlcXl1TzV4TUFSU3BCTVVXMjQ9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUVsMmNieTBHa0dPSXlVRDMzRnlGK0VvQUxwL3hZQi9Ba1d0cUdXcXhXWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSERXQ0ttU0IrSmh6d0FoTDhYQ21vU3U2MGZrRzdiWUMvUUQyNTE3YUpoRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ikc5VWZSb3R5dmFlWmxUTzBOek84V3RoVC8xdE1BWjJVaDROUkduM2FsNmRzb28xRUc5OWw1eVdiN1h5RndMNys5dkF2VWNXb3Q3M25jYjg0a3dpUkFnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NjUsImFkdlNlY3JldEtleSI6Ijdici82WkZwTS8zSUZsWjVWaVV2VFJDK3VFTW4wNUg0NVVtYzU3WnJ2THM9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IlJMR1ZRS0tOIiwibWUiOnsiaWQiOiI5MjMyOTU5MDE3OTk6OEBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJib3QiLCJsaWQiOiI0MDQ2NzgzNjIzMTg5NDo4QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDT09NcHlRUSt2ajF4UVlZQWlBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoidWwzWVMvdE8yZzZuTm5rYm01QjNRNUM4RHF4RnpROTNhbm9DdnhMK1pUWT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiWUZUaHNtcHBadWFhaHRuYk4vUDR4eXpDdDJkTm5DbGlPUEhCeUMvZElMZXc5VVJwWUdoQmpacXhCeGpZaVVsUUZvVmlmVmdBS1ZsQTFaYnpRbWRpQXc9PSIsImRldmljZVNpZ25hdHVyZSI6IkJMcCtmbGh0ZVBXenp6TWEwUG9RcGk1ejErZmZVVmFmTkdDcytxWTRKQ3R2ZGxHUTRjTFJJaG4rNEVNOXpZWmVwUDV5ajBXbkRXbXQ2K042Q2hLeUN3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTIzMjk1OTAxNzk5OjhAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYnBkMkV2N1R0b09welo1RzV1UWQwT1F2QTZzUmMwUGQycDZBcjhTL21VMiJ9fV0sInBsYXRmb3JtIjoic21iYSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FJSURRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU3MjQ4NjM3LCJsYXN0UHJvcEhhc2giOiIxSzRoSDQiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUdMLyJ9waz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVnM4b1F1OTc3WDFIRVk1YXhZUncxUFlSUVg3d3NIR1RYWXlwTUFpQVYwdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4STJOMk1nNTNxSEY5Ny9ISER6ZzBoVG9TTGlHUVRRMzZ3SExBRlJNSW1ZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJkeHQvV0dJeDJ5Snd4bms2Wk5xbnRQWHRBQVZuWHBFUWtJMVBGcVVwWDBFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdJVUoyd2h0UnFveEN2L1lBejMwYTJCMkdXOU4wdnNxVEdPWStuSG5RbFU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZqQWpRcHkxZ05BV2FORzI5UVZFVkhiVVRYU2dpRGtFN3dHUGgrZEkwaW89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkNmbW10VEMzTG00SEtyc2RaM1B3ajN0azlHbTFMaFNqcDVrNHp6MVNtbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWDNIallMSlBiV211M0M2dWx4cGlEZ3NwR2NobFd1MU5qVkt5TkhtZHpBMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitiVEMxS1Npc2JQQkk3aXNxa3d5VU1SNGNFcFF4aFdYa1RSWW1SQ3NTbHoxdnZDK1BvWnlLajUwTlFwTCsyNW1zUTFudnRiNWdOdXd2T1l3WGJySmdRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAyLCJhZHZTZWNyZXRLZXkiOiJkQTBkbWx2Z1RiZ1Y1SjRnM3dvTjBOZ2ExdDN0Q3g0cHBBYmloODQ5NjJFPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJBVDNRVzNSSiIsIm1lIjp7ImlkIjoiOTIzMjI5ODU0NzExOjVAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiI1OTI3NDkyNzU4MzM5Nzo1QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUEhUeDVvRkVMbjA5Y1VHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiOWJkL2thQnIwK0hhbjlkUTNvY3ZrNkwyMUN3UmMvNVZMRTBxWC9CY2FpMD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiQU1HaHRib0IrQUEwMkhSOUhOZCtOZ1pSNlFTbGY3Z1lUTTREQWZoaERWdm1RL0haK0tZbDdwcTVoT3hiRHUyUXhiRER4Yi9ZbEFQUEZ1dTNDQXlkRGc9PSIsImRldmljZVNpZ25hdHVyZSI6IkY2VlVMOFJUMFZtOUlwTituaHBkYmc5SitrS0dvTVdvL0p3bmtGcHc4a0VTRDZZZHBMenlobTZtL0xiQWUwdE9QVHBqcXovcmJ4aHF1alRzaWNmU2p3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTIzMjI5ODU0NzExOjVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZlczZjVHZ2E5UGgycC9YVU42SEw1T2k5dFFzRVhQK1ZTeE5LbC93WEdvdCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FnSUJRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU3MjQ4MDYxLCJsYXN0UHJvcEhhc2giOiJQV2s1QiJ9",
// add your Session Id 
AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN || "true",
// make true or false status auto seen
AUTO_STATUS_REPLY: process.env.AUTO_STATUS_REPLY || "true",
// make true if you want auto reply on status 
AUTO_STATUS_REACT: process.env.AUTO_STATUS_REACT || "true",
// make true if you want auto reply on status 
AUTO_STATUS_MSG: process.env.AUTO_STATUS_MSG || "*SEEN YOUR STATUS BY 𝙀3-WAQAR-𝙈𝘿 ♥️☺️*",
// set the auto reply massage on status reply  
ANTI_DELETE: process.env.ANTI_DELETE || "true",
// set true false for anti delete     
ANTI_DEL_PATH: process.env.ANTI_DEL_PATH || "inbox", 
// change it to 'same' if you want to resend deleted message in same chat     
WELCOME: process.env.WELCOME || "true",
// true if want welcome and goodbye msg in groups    
ADMIN_EVENTS: process.env.ADMIN_EVENTS || "true",
// make true to know who dismiss or promoted a member in group
ANTI_LINK: process.env.ANTI_LINK || "true",
// make anti link true,false for groups 
MENTION_REPLY: process.env.MENTION_REPLY || "false",
// make true if want auto voice reply if someone menetion you 
MENU_IMAGE_URL: process.env.MENU_IMAGE_URL || "https://files.catbox.moe/iyudhj.jpg",
// add custom menu and mention reply image url
PREFIX: process.env.PREFIX || ".",
// add your prifix for bot   
BOT_NAME: process.env.BOT_NAME || "E3-WAQAR-MD",
// add bot namw here for menu
STICKER_NAME: process.env.STICKER_NAME || "E3-WAQAR-MD",
// type sticker pack name 
CUSTOM_REACT: process.env.CUSTOM_REACT || "true",
// make this true for custum emoji react    
CUSTOM_REACT_EMOJIS: process.env.CUSTOM_REACT_EMOJIS || "💝,💖,💗,❤️‍🩹,❤️,🧡,💛,💚,💙,💜,🤎,🖤,🤍",
// chose custom react emojis by yourself 
DELETE_LINKS: process.env.DELETE_LINKS || "true",
// automatic delete links witho remove member 
OWNER_NUMBER: process.env.OWNER_NUMBER || "923495178663",
// add your bot owner number
OWNER_NAME: process.env.OWNER_NAME || "*E3-WAQAR-MD Official*",
// add bot owner name
DESCRIPTION: process.env.DESCRIPTION || "*© ᴘᴏᴡᴇʀᴇᴅ ʙʏ E3-WAQAR-MD Official ❣️*",
// add bot owner name    
ALIVE_IMG: process.env.ALIVE_IMG || "https://files.catbox.moe/iyudhj.jpg",
// add img for alive msg
LIVE_MSG: process.env.LIVE_MSG || "> Apni Had May Raho Batmeez Insan 🫣",
// add alive msg here 
READ_MESSAGE: process.env.READ_MESSAGE || "false",
// Turn true or false for automatic read msgs
AUTO_REACT: process.env.AUTO_REACT || "true",
// make this true or false for auto react on all msgs
ANTI_BAD: process.env.ANTI_BAD || "true",
// false or true for anti bad words  
MODE: process.env.MODE || "public",
// make bot public-private-inbox-group 
ANTI_LINK_KICK: process.env.ANTI_LINK_KICK || "true",
// make anti link true,false for groups 
AUTO_STICKER: process.env.AUTO_STICKER || "false",
// make true for automatic stickers 
AUTO_REPLY: process.env.AUTO_REPLY || "true",
// make true or false automatic text reply 
ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "false",
// maks true for always online 
PUBLIC_MODE: process.env.PUBLIC_MODE || "true",
// make false if want private mod
AUTO_TYPING: process.env.AUTO_TYPING || "false",
// true for automatic show typing   
READ_CMD: process.env.READ_CMD || "false",
// true if want mark commands as read 
DEV: process.env.DEV || "923495178663",
//replace with your whatsapp number        
ANTI_VV: process.env.ANTI_VV || "true",
// true for anti once view 
AUTO_RECORDING: process.env.AUTO_RECORDING || "false"
// make it true for auto recoding 
};
